updated with Rational{Int}
JuliaSmoothOptimizers/SolverTest.jl pull request #62
Opened 2023-12-23 17:38 UTC by Jay-sanjay

This PR is related to issue #56 

## PR CheckList

- [x] added  Rational{Int} check for unconstrained.jl and bound-constrained.jl

2023-12-24 13:08 UTC, tmigot requested changes
Thanks @Jay-sanjay that looks great!
Could you also do the same for these two?
- [ ] https://github.com/Jay-sanjay/SolverTest.jl/blob/a695b84058251b435435feb8dd37df356dfd4f05/src/nls/unconstrained.jl#L5
- [ ] https://github.com/Jay-sanjay/SolverTest.jl/blob/a695b84058251b435435feb8dd37df356dfd4f05/src/nls/bound-constrained.jl#L5

2023-12-24 13:08 UTC, tmigot commented on src/nlp/bound-constrained.jl
> +  D = Diagonal([Rational{Int}(1//10 + 9//10 * (i - 1) / (n - 1)) for i = 1:n])
```suggestion
  D = Diagonal([1//10 + 9//10 * (i - 1) // (n - 1) for i = 1:n])
```

2023-12-24 13:08 UTC, tmigot commented on src/nlp/unconstrained.jl
> +  D = Diagonal([Rational{Int}(1//10 + 9//10 * (i - 1) / (n - 1)) for i = 1:n])
```suggestion
  D = Diagonal([1//10 + 9//10 * (i - 1) // (n - 1) for i = 1:n])
```

2023-12-25 07:45 UTC, Jay-sanjay commented
Thank you @tmigot sir, I guess I just missed to update that nls file before asking for the review :)

2023-12-25 07:48 UTC, Jay-sanjay commented
Thank you @tmigot sir, I guess I just missed to update that nls file before asking for the review :)
Sorry for that, I will try to recheck things before asking for the review

2023-12-25 08:12 UTC, merged